"""add ml_model_state table

Revision ID: 1ad7fa040cd9
Revises: 90be3ce67959
Create Date: 2026-09-13 23:11:14.520674

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1ad7fa040cd9"
down_revision: Union[str, Sequence[str], None] = "90be3ce67959"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ml_model_state",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("categorizations_since_train", sa.Integer(), nullable=False),
        sa.Column("last_trained_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ml_model_state")
    # ### end Alembic commands ###
