"""add csv_profile table

Revision ID: 246dcdcac806
Revises: 8cc9c1cc0191
Create Date: 2026-02-20 19:10:11.592253

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "246dcdcac806"
down_revision: Union[str, Sequence[str], None] = "8cc9c1cc0191"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "csv_profile",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("delimiter", sa.String(), nullable=False),
        sa.Column("date_format", sa.String(), nullable=False),
        sa.Column("decimal_comma", sa.Boolean(), nullable=False),
        sa.Column("column_map", sa.JSON(), server_default="{}", nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("csv_profile")
    # ### end Alembic commands ###
