"""normalize sa_types

Revision ID: 2ba8a55950a5
Revises: badbf6d42459
Create Date: 2025-12-30 16:50:15.650350

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '2ba8a55950a5'
down_revision: Union[str, Sequence[str], None] = 'badbf6d42459'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
