"""add row_filters to csv_profile

Revision ID: 2c39994ff739
Revises: cb89e7b327d5
Create Date: 2026-06-07 14:29:12.085616

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2c39994ff739"
down_revision: Union[str, Sequence[str], None] = "cb89e7b327d5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("csv_profile", sa.Column("row_filters", sa.JSON(), nullable=True))
    op.add_column(
        "csv_profile", sa.Column("row_exclude_filters", sa.JSON(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("csv_profile", "row_exclude_filters")
    op.drop_column("csv_profile", "row_filters")
    # ### end Alembic commands ###
