"""add recurring_pattern table

Revision ID: 520132a95287
Revises: 8412074524e5
Create Date: 2026-02-18 12:31:43.191095

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "520132a95287"
down_revision: Union[str, Sequence[str], None] = "8412074524e5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "recurring_pattern",
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("payee", sa.String(length=255), nullable=False),
        sa.Column("typical_amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("frequency", sa.String(length=20), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=3, scale=2), nullable=False),
        sa.Column("last_seen", sa.Date(), nullable=False),
        sa.Column("occurrence_count", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("user_confirmed", sa.Boolean(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["account.id"],
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["category.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "account_id", "payee", "frequency", name="uq_recurring_pattern"
        ),
    )
    op.create_index(
        op.f("ix_recurring_pattern_account_id"),
        "recurring_pattern",
        ["account_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_recurring_pattern_account_id"), table_name="recurring_pattern"
    )
    op.drop_table("recurring_pattern")
    # ### end Alembic commands ###
