"""add app_settings and account opening balance fields

Revision ID: 67f4149462f0
Revises: 90be3ce67959
Create Date: 2026-09-13 21:30:09.526432

"""

from datetime import datetime, timezone
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "67f4149462f0"
down_revision: Union[str, Sequence[str], None] = "90be3ce67959"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _stamp_onboarding_completed_for_existing_users(bind: sa.engine.Connection) -> None:
    """Existing databases (>= 1 account already) skip the setup wizard.

    Only fresh installs (no accounts yet) should see onboarding_completed_at
    left NULL, since that is what triggers the first-run wizard redirect.
    """
    meta = sa.MetaData()
    account = sa.Table("account", meta, autoload_with=bind)
    app_settings = sa.Table("app_settings", meta, autoload_with=bind)

    account_count = bind.execute(
        sa.select(sa.func.count()).select_from(account)
    ).scalar()
    if not account_count:
        return

    bind.execute(
        sa.insert(app_settings).values(
            id=1,
            onboarding_completed_at=datetime.now(timezone.utc),
            onboarding_skipped=False,
            default_currency="EUR",
            locale=None,
        )
    )


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("onboarding_completed_at", sa.DateTime(), nullable=True),
        sa.Column("onboarding_skipped", sa.Boolean(), nullable=False),
        sa.Column("default_currency", sa.String(length=3), nullable=False),
        sa.Column("locale", sa.String(length=10), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###

    _stamp_onboarding_completed_for_existing_users(op.get_bind())


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("app_settings")
    # ### end Alembic commands ###
