"""add_account_type

Revision ID: 78f5bfccf4f0
Revises: 9719f1de18e4
Create Date: 2026-09-13 19:53:30.615422

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "78f5bfccf4f0"
down_revision: Union[str, Sequence[str], None] = "9719f1de18e4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("account", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "account_type",
                sa.String(length=16),
                server_default="bank",
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("account", schema=None) as batch_op:
        batch_op.drop_column("account_type")

    # ### end Alembic commands ###
