"""add watch folder config

Revision ID: 82014b421e83
Revises: 246dcdcac806
Create Date: 2026-03-04 20:51:15.196215

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "82014b421e83"
down_revision: Union[str, Sequence[str], None] = "246dcdcac806"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "watch_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("root_path", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "watch_folder_config",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("subfolder_name", sa.String(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("profile_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["account.id"],
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["csv_profile.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("subfolder_name"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("watch_folder_config")
    op.drop_table("watch_settings")
    # ### end Alembic commands ###
