"""add cost_type to category

Revision ID: 8412074524e5
Revises: d282daea485b
Create Date: 2026-02-18 12:24:09.092039

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8412074524e5"
down_revision: Union[str, Sequence[str], None] = "d282daea485b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "category", sa.Column("cost_type", sa.String(length=10), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("category", "cost_type")
    # ### end Alembic commands ###
