"""add_opening_balance_to_account

Revision ID: 8cc9c1cc0191
Revises: c1022c065ce6
Create Date: 2026-02-18 22:44:00.257493

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8cc9c1cc0191"
down_revision: Union[str, Sequence[str], None] = "c1022c065ce6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "account",
        sa.Column("opening_balance", sa.Numeric(precision=14, scale=2), nullable=True),
    )
    op.add_column(
        "account", sa.Column("opening_balance_date", sa.Date(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("account", "opening_balance_date")
    op.drop_column("account", "opening_balance")
    # ### end Alembic commands ###
