"""add_transfer_candidate_active_indexes

Revision ID: 90be3ce67959
Revises: 78f5bfccf4f0
Create Date: 2026-09-13 20:31:04.119130

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "90be3ce67959"
down_revision: Union[str, Sequence[str], None] = "78f5bfccf4f0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _dismiss_duplicate_active_candidates(bind: sa.engine.Connection) -> None:
    """Data cleanup, required before the indexes below can be created.

    Pre-existing bug (transfer_detection.py had no is_transfer guard, and
    confirm_transfer had no validation at all): a transaction could end up
    referenced by more than one active (pending/confirmed) TransferCandidate
    row. On this database that's not hypothetical — real duplicate rows
    exist. For each transaction id, keep the earliest-created (lowest id)
    active row that claims it and dismiss any later row that claims the same
    id again. This never touches Transaction.is_transfer — every affected
    transaction already has it set correctly from whichever row confirmed it
    first, so reports are unaffected; only the redundant candidate bookkeeping
    rows are cleaned up.
    """
    meta = sa.MetaData()
    tc = sa.Table("transfer_candidate", meta, autoload_with=bind)

    rows = bind.execute(
        sa.select(tc.c.id, tc.c.from_transaction_id, tc.c.to_transaction_id)
        .where(tc.c.status.in_(("pending", "confirmed")))
        .order_by(tc.c.id)
    ).all()

    seen_from: set[int] = set()
    seen_to: set[int] = set()
    dismiss_ids: list[int] = []
    for row in rows:
        if row.from_transaction_id in seen_from or row.to_transaction_id in seen_to:
            dismiss_ids.append(row.id)
            continue
        seen_from.add(row.from_transaction_id)
        seen_to.add(row.to_transaction_id)

    if dismiss_ids:
        bind.execute(
            sa.update(tc).where(tc.c.id.in_(dismiss_ids)).values(status="dismissed")
        )
        print(
            f"add_transfer_candidate_active_indexes: dismissed {len(dismiss_ids)} "
            "duplicate-active transfer_candidate row(s) (is_transfer left untouched) "
            f"— ids: {dismiss_ids}"
        )


def upgrade() -> None:
    """Upgrade schema."""
    _dismiss_duplicate_active_candidates(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("transfer_candidate", schema=None) as batch_op:
        batch_op.create_index(
            "uq_transfer_candidate_active_from",
            ["from_transaction_id"],
            unique=True,
            sqlite_where=sa.text("status IN ('pending', 'confirmed')"),
        )
        batch_op.create_index(
            "uq_transfer_candidate_active_to",
            ["to_transaction_id"],
            unique=True,
            sqlite_where=sa.text("status IN ('pending', 'confirmed')"),
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("transfer_candidate", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_transfer_candidate_active_to",
            sqlite_where=sa.text("status IN ('pending', 'confirmed')"),
        )
        batch_op.drop_index(
            "uq_transfer_candidate_active_from",
            sqlite_where=sa.text("status IN ('pending', 'confirmed')"),
        )

    # ### end Alembic commands ###
