"""add_source_to_transfer_candidate

Revision ID: 9719f1de18e4
Revises: e8c8c7121cfd
Create Date: 2026-09-13 18:24:30.984417

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9719f1de18e4"
down_revision: Union[str, Sequence[str], None] = "e8c8c7121cfd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("transfer_candidate", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "source", sa.String(length=16), server_default="auto", nullable=False
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("transfer_candidate", schema=None) as batch_op:
        batch_op.drop_column("source")

    # ### end Alembic commands ###
