"""add_transfer_fields

Revision ID: c1022c065ce6
Revises: 520132a95287
Create Date: 2026-02-18 22:14:56.198888

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c1022c065ce6"
down_revision: Union[str, Sequence[str], None] = "520132a95287"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transfer_candidate",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("from_transaction_id", sa.Integer(), nullable=False),
        sa.Column("to_transaction_id", sa.Integer(), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=3, scale=2), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.ForeignKeyConstraint(
            ["from_transaction_id"],
            ["transaction.id"],
        ),
        sa.ForeignKeyConstraint(
            ["to_transaction_id"],
            ["transaction.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "from_transaction_id",
            "to_transaction_id",
            name="uq_transfer_candidate_pair",
        ),
    )
    op.create_index(
        op.f("ix_transfer_candidate_from_transaction_id"),
        "transfer_candidate",
        ["from_transaction_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transfer_candidate_to_transaction_id"),
        "transfer_candidate",
        ["to_transaction_id"],
        unique=False,
    )
    op.add_column(
        "transaction",
        sa.Column(
            "is_transfer", sa.Boolean(), nullable=False, server_default=sa.false()
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transaction", "is_transfer")
    op.drop_index(
        op.f("ix_transfer_candidate_to_transaction_id"), table_name="transfer_candidate"
    )
    op.drop_index(
        op.f("ix_transfer_candidate_from_transaction_id"),
        table_name="transfer_candidate",
    )
    op.drop_table("transfer_candidate")
    # ### end Alembic commands ###
